
import type { LucideIcon } from 'lucide-react';
import {
  LayoutDashboard,
  CalendarPlus,
  CheckCircle2,
  Briefcase,
  Lightbulb,
  Users,
  ListChecks,
  ClipboardList,
  UserCheck,
  Hourglass,
  BarChartBig,
  ShieldCheck,
  ShieldX,
  LogIn,
  LogOut,
  CalendarOff,
  UserMinus,
  Clock,
  CalendarDays,
  Activity,
  ListFilter,
  Eye,
  XCircle, 
  CalendarClock,
  Loader2,
  Calculator,
  Save,
  DollarSign,
  CalendarCheck2,
  Sheet, // Added Sheet icon for reports
  UserPlus,
  KeyRound,
  FileDown,
  Settings, // Added Settings icon
  Trophy, // Added Trophy Icon
  Send,
  UploadCloud,
  FileText,
  AlertTriangle,
  BookOpenCheck,
  Bell, // Added Bell icon
} from 'lucide-react';

export const iconMap: { [key: string]: LucideIcon } = {
  LayoutDashboard,
  CalendarPlus,
  CheckCircle2,
  Briefcase,
  Lightbulb,
  Users,
  ListChecks,
  ClipboardList,
  UserCheck,
  Hourglass,
  BarChartBig,
  ShieldCheck,
  ShieldX,
  LogIn,
  LogOut,
  CalendarOff,
  UserMinus,
  Clock,
  CalendarDays,
  Activity,
  ListFilter,
  Eye,
  XCircle,
  CalendarClock,
  Loader2,
  Calculator,
  Save,
  DollarSign,
  CalendarCheck2,
  Sheet, // Added Sheet icon for reports
  UserPlus,
  KeyRound,
  FileDown,
  Settings, // Added Settings icon
  Trophy, // Added Trophy Icon
  Send,
  UploadCloud,
  FileText,
  AlertTriangle,
  BookOpenCheck,
  Bell,
};

    