// This is a placeholder file and is not used in the app.
// The purpose of this file is to track icon usage to prevent
// breaking changes when new icons are added to the library.

import {
  MoreHorizontal,
  Search,
  Users,
  PlusCircle,
  Edit3,
  Trash2,
  AlertCircle,
  Loader2,
  UserCheck,
  UserX,
  Clock,
  DollarSign,
  Calendar,
  CheckIcon,
  ChevronsUpDown,
  UserPlus,
  ShieldCheck,
  UserMinus,
  Eye,
  EyeOff,
  KeyRound,
  UploadCloud,
  File,
  Download,
  Filter,
  ArrowLeft,
  ArrowRight,
  UserCircle2,
  Phone,
  Briefcase,
  Mail,
  MailWarning,
  PhoneCall,
  GitBranch,
  ZoomIn,
  ZoomOut,
} from "lucide-react";
